plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.sig.postsapp'
    compileSdk {
        version = release(37) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId "com.sig.postsapp"
        minSdk 29
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_18
        targetCompatibility JavaVersion.VERSION_18
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
    // Retrofit & OkHttp
    implementation libs.retrofit
    implementation libs.converter.gson
    implementation libs.gson
    implementation libs.okhttp
    implementation libs.logging.interceptor
    // Dagger Hilt
    implementation libs.hilt.android
    annotationProcessor libs.hilt.compiler
    // Navigation Component
    implementation libs.navigation.fragment
    implementation libs.navigation.ui

}